# Generated by Django 5.2.9 on 2025-12-23 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentomedico',
            name='fecha_de_creacion',
        ),
        migrations.RemoveField(
            model_name='departamentomedico',
            name='nro_dpto',
        ),
        migrations.RemoveField(
            model_name='departamentomedico',
            name='nro_empleados',
        ),
        migrations.AlterField(
            model_name='departamentomedico',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.departamentomedico')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambulance.medico')),
            ],
        ),
    ]
