# Generated by Django 5.2.9 on 2025-12-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0003_clase_profesor_remove_medico_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(default=18, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
